language: perl
perl:
 - "5.16"
 - "5.14"
 - "5.12"
 - "5.10"
 - "5.8"
install: "cpanm POSIX IO::Uncompress::AnyInflate IO::Compress::Gzip Getopt::Long List::Util"
script: "./test/run_tests.sh"
notifications:
  slack:
    rooms:
      - wtsi-hgi:z69CHHY2YK0TegYcMmH8uHTE#dev
      
